'use strict';

const test = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { itemsOf, toolLine, resultText, typedText, checkTranscript, projectFolder, createLive } = require('../src/main/claude/live');

const user = (content, extra = {}) => ({ type: 'user', message: { role: 'user', content }, ...extra });
const assistant = (content, extra = {}) => ({ type: 'assistant', message: { role: 'assistant', content }, ...extra });

test('what the person typed, Claude\'s replies, the tools it ran and what they gave back become items', () => {
  assert.deepStrictEqual(itemsOf(user('fix the login bug')), [{ kind: 'you', text: 'fix the login bug' }]);
  assert.deepStrictEqual(itemsOf(user([{ type: 'text', text: 'and add a test' }])), [{ kind: 'you', text: 'and add a test' }]);
  assert.deepStrictEqual(itemsOf(assistant([
    { type: 'thinking', thinking: 'hmm' },
    { type: 'text', text: '  I will look at it.  ' },
    { type: 'tool_use', name: 'Bash', input: { command: 'npm test\n  -- --watch' } },
  ])), [{ kind: 'claude', text: 'I will look at it.' }, { kind: 'tool', text: '$ npm test -- --watch' }]);
  assert.deepStrictEqual(itemsOf(user([{ type: 'tool_result', content: 'all 12 pass' }])), [{ kind: 'result', text: 'all 12 pass' }]);
  assert.deepStrictEqual(itemsOf(user([{ type: 'tool_result', content: [{ type: 'text', text: 'boom' }], is_error: true }])),
    [{ kind: 'result', text: 'boom', error: true }]);
  assert.deepStrictEqual(itemsOf(user('[Request interrupted by user]')), [{ kind: 'event', text: 'Stopped' }]);
});

test("a subagent's lines, Claude Code's own notes, other kinds of lines and anything malformed make no items", () => {
  for (const entry of [
    assistant([{ type: 'text', text: 'from a subagent' }], { isSidechain: true }),
    user('a note', { isMeta: true }),
    user('<system-reminder>be nice</system-reminder>'),
    user('<local-command-stdout>ok</local-command-stdout>'),
    user('Caveat: the messages below were generated by the user while running local commands.'),
    { type: 'attachment', attachment: {} },
    { type: 'summary', summary: 'x' },
    assistant([{ type: 'text', text: '   ' }]),
    user(null),
    null,
    'text',
    [],
  ]) {
    assert.deepStrictEqual(itemsOf(entry), [], JSON.stringify(entry));
  }
});

test('a slash command shows as the command the person typed', () => {
  assert.strictEqual(typedText('<command-name>/review</command-name><command-args>42</command-args>'), '/review 42');
  assert.strictEqual(typedText('<command-name>/clear</command-name><command-args></command-args>'), '/clear');
  assert.strictEqual(typedText('<command-name></command-name>'), null);
});

test("each tool's line says what it did in a few words", () => {
  assert.strictEqual(toolLine('Read', { file_path: '/Users/a/projects/app/src/main.js' }), 'Read src/main.js');
  assert.strictEqual(toolLine('Edit', { file_path: 'C:\\code\\app\\index.js' }), 'Edit app/index.js');
  assert.strictEqual(toolLine('Grep', { pattern: 'TODO' }), 'Grep TODO');
  assert.strictEqual(toolLine('WebSearch', { query: 'electron tray' }), 'Search electron tray');
  assert.strictEqual(toolLine('Agent', { description: 'Find the bug' }), 'Agent: Find the bug');
  assert.strictEqual(toolLine('TodoWrite', {}), 'Updated the to-do list');
  assert.strictEqual(toolLine('mcp__x__y', null), 'mcp__x__y');
  assert.strictEqual(toolLine(undefined, undefined), 'A tool');
  assert.ok(toolLine('Bash', { command: 'x'.repeat(500) }).length <= 201, 'a long command is cut');
});

test('what a tool gave back is cut to its first lines', () => {
  const long = Array.from({ length: 20 }, (_, i) => `line ${i + 1}`).join('\n');
  assert.strictEqual(resultText(long), `${long.split('\n').slice(0, 8).join('\n')}\n… 12 more lines`);
  assert.strictEqual(resultText([{ type: 'image' }, { type: 'text', text: 'a' }, { type: 'text', text: 'b' }]), 'a\nb');
  assert.strictEqual(resultText(undefined), '');
  assert.ok(resultText('y'.repeat(5000)).length <= 801);
});

test("only a .jsonl file inside Claude Code's config folder is read", () => {
  const dir = path.join(os.tmpdir(), 'claude-home');
  assert.strictEqual(checkTranscript(path.join(dir, 'projects', 'p', 'a.jsonl'), [dir]), path.join(dir, 'projects', 'p', 'a.jsonl'));
  for (const file of [
    path.join(dir, 'projects', 'p', 'a.json'),
    path.join(os.tmpdir(), 'elsewhere', 'a.jsonl'),
    path.join(dir, '..', 'claude-home-2', 'a.jsonl'),
    path.join(dir, 'projects', '..', '..', 'etc', 'a.jsonl'),
    'projects/p/a.jsonl',
    '',
    null,
  ]) {
    assert.strictEqual(checkTranscript(file, [dir]), null, String(file));
  }
});

test("Claude Code's name for a project folder", () => {
  assert.strictEqual(projectFolder('/Users/akshat/projects/buddy'), '-Users-akshat-projects-buddy');
  assert.strictEqual(projectFolder('/Users/a/my.app_2'), '-Users-a-my-app-2');
});

/** A Claude Code config folder in a temp folder, with one running session (this test's own process) and its file. */
function claudeHome(t, lines) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'buddy-live-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const cwd = '/Users/a/projects/shop';
  const id = '11111111-2222-3333-4444-555555555555';
  fs.mkdirSync(path.join(dir, 'sessions'));
  fs.writeFileSync(path.join(dir, 'sessions', `${process.pid}.json`), JSON.stringify({
    pid: process.pid, sessionId: id, cwd, name: 'shop-x', status: 'busy', kind: 'interactive', updatedAt: 1000,
  }));
  fs.writeFileSync(path.join(dir, 'sessions', '999999.json'), '{ not json');
  const transcript = path.join(dir, 'projects', projectFolder(cwd), `${id}.jsonl`);
  fs.mkdirSync(path.dirname(transcript), { recursive: true });
  fs.writeFileSync(transcript, lines.map((l) => JSON.stringify(l)).join('\n') + '\n');
  return { dir, id, cwd, transcript };
}

test('the sessions running now are found, with their terminal, and read from their start', async (t) => {
  const home = claudeHome(t, [user('hi'), assistant([{ type: 'text', text: 'Hello!' }])]);
  const live = createLive({ configDirs: () => [home.dir], now: () => 2000, ttys: async (pids) => ({ [pids[0]]: 'ttys004' }) });
  await live.discover();
  assert.deepStrictEqual(live.list(), [{ id: home.id, name: 'shop-x', title: null, status: 'working', canTalk: true }]);
  assert.deepStrictEqual(live.target(home.id), { tty: 'ttys004', name: 'shop-x' });

  const changed = [];
  live.onChange((id) => changed.push(id));
  await live.refresh(home.id);
  assert.deepStrictEqual(live.view(home.id).items, [{ id: 1, kind: 'you', text: 'hi' }, { id: 2, kind: 'claude', text: 'Hello!' }]);
  assert.deepStrictEqual(changed, [home.id]);

  // New lines: only they are read; a line still being written waits for its end.
  const tool = JSON.stringify(assistant([{ type: 'tool_use', name: 'Bash', input: { command: 'ls' } }]));
  fs.appendFileSync(home.transcript, `${tool}\n${tool.slice(0, 10)}`);
  await live.refresh(home.id);
  assert.deepStrictEqual(live.view(home.id).items.slice(2), [{ id: 3, kind: 'tool', text: '$ ls' }]);
  fs.appendFileSync(home.transcript, `${tool.slice(10)}\n`);
  await live.refresh(home.id);
  assert.strictEqual(live.view(home.id).items.length, 4);
  await live.refresh(home.id);
  assert.deepStrictEqual(changed, [home.id, home.id, home.id], 'nothing new: nobody is told');
});

test('a session whose process has stopped leaves the list', async (t) => {
  const home = claudeHome(t, []);
  let running = true;
  const live = createLive({ configDirs: () => [home.dir], isAlive: () => running, ttys: async () => ({}) });
  await live.discover();
  assert.strictEqual(live.list().length, 1);
  assert.strictEqual(live.list()[0].canTalk, false, 'no terminal known: Buddy cannot type into it');
  running = false;
  await live.discover();
  assert.deepStrictEqual(live.list(), []);
});

test('hook events add a session and move its status; the terminal comes from the hook', async (t) => {
  const home = claudeHome(t, [user('go')]);
  fs.rmSync(path.join(home.dir, 'sessions'), { recursive: true });
  let clock = 1000;
  const live = createLive({ configDirs: () => [home.dir], now: () => clock });
  const event = (name, extra = {}) => ({ name, sessionId: home.id, folder: 'shop', cwd: home.cwd, transcript: home.transcript, tty: '', ...extra });
  live.hear(event('UserPromptSubmit', { tty: 'ttys002' }));
  assert.deepStrictEqual(live.list(), [{ id: home.id, name: 'shop', title: null, status: 'working', canTalk: true }]);
  for (const [name, status] of [['PermissionRequest', 'waiting'], ['PreToolUse', 'working'], ['Stop', 'done'], ['StopFailure', 'failed']]) {
    live.hear(event(name, { tty: 'not a tty' }));
    assert.strictEqual(live.list()[0].status, status, name);
  }
  assert.strictEqual(live.target(home.id).tty, 'ttys002', 'a bad tty does not replace a good one');
  await live.refresh(home.id);
  assert.deepStrictEqual(live.view(home.id).items, [{ id: 1, kind: 'you', text: 'go' }]);

  live.hear(event('Stop', { transcript: '/etc/passwd.jsonl' }));
  await live.refresh(home.id);
  assert.strictEqual(live.view(home.id).items.length, 1, 'a file outside the config folder is never read');

  clock += 7 * 60 * 60 * 1000;
  assert.deepStrictEqual(live.list(), [], 'quiet for hours: forgotten');
  live.hear(event('SessionEnd'));
  assert.deepStrictEqual(live.list(), [], 'an ended session is not listed');
});

test('a session read the first time from the middle of a long file starts at a whole line', async (t) => {
  const { FIRST_READ } = require('../src/main/claude/live');
  const filler = user('x'.repeat(1000));
  const count = Math.ceil(FIRST_READ / 1000) + 5;
  const home = claudeHome(t, [...Array.from({ length: count }, () => filler), user('the newest')]);
  const live = createLive({ configDirs: () => [home.dir], ttys: async () => ({}) });
  await live.discover();
  await live.refresh(home.id);
  const items = live.view(home.id).items;
  assert.deepStrictEqual(items[items.length - 1].text, 'the newest');
  assert.ok(items.every((item) => item.kind === 'you'), 'no half line was read');
});

test("the session's title, as its terminal tab shows it: the newest one Claude Code gave it, read from the end of its file", async (t) => {
  const { titleIn } = require('../src/main/claude/live');
  assert.strictEqual(titleIn('{"type":"ai-title","aiTitle":"First"}\n{"type":"ai-title","aiTitle":"Fix the login bug"}'), 'Fix the login bug');
  assert.strictEqual(titleIn('{"type":"ai-title","aiTitle":"Say \\"hi\\""}'), 'Say "hi"');
  assert.strictEqual(titleIn('{"type":"user"}'), null);
  assert.strictEqual(titleIn('{"type":"ai-title","aiTitle":"   "}'), null);
  assert.strictEqual(titleIn('{"type":"ai-title","aiTitle":"' + 'x'.repeat(300) + '"}').length, 121, 'a long one is cut');

  const home = claudeHome(t, [user('hi'), { type: 'ai-title', aiTitle: 'Link automatic settings page', sessionId: 'x' }]);
  const live = createLive({ configDirs: () => [home.dir], ttys: async () => ({}) });
  await live.discover();
  assert.strictEqual(live.list()[0].title, 'Link automatic settings page', 'listed with it, before it is opened');
  fs.appendFileSync(home.transcript, `${JSON.stringify({ type: 'ai-title', aiTitle: 'Body display in notch area' })}\n`);
  await live.refresh(home.id);
  assert.strictEqual(live.view(home.id).title, 'Body display in notch area', 'renamed as the work goes on');
});
